package SmileOne.model;
// Generated Sep 14, 2020 10:34:27 AM by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

/**
 * Inboxes generated by hbm2java
 */
public class Inboxes  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    private int id;

    private String message;
    private String sender;
    private Integer status;
    private Date createDate;
    private String trxId;

    public Inboxes() {
    }

    public Inboxes(String message, String sender, Integer status, Date createDate, String trxId) {
       this.message = message;
       this.sender = sender;
       this.status = status;
       this.createDate = createDate;
       this.trxId = trxId;
    }
   
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getTrxId() {
        return this.trxId;
    }
    
    public void setTrxId(String trxId) {
        this.trxId = trxId;
    }




}


