package SmileOne.model;
// Generated Sep 14, 2020 10:34:27 AM by Hibernate Tools 4.3.1


import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.util.Date;

/**
 * Outboxes generated by hbm2java
 */
public class Outboxes  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy= GenerationType.AUTO)
    private int id;

    private String message;
    private String receiver;
    private Date createDate;
    private Integer inboxId;

    public Outboxes() {
    }

    public Outboxes(String message, String receiver, Date createDate, Integer inboxId) {
       this.message = message;
       this.receiver = receiver;
       this.createDate = createDate;
       this.inboxId = inboxId;
    }
   
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getInboxId() {
        return this.inboxId;
    }
    
    public void setInboxId(Integer inboxId) {
        this.inboxId = inboxId;
    }




}


