package SmileOne;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class loginToTopUp {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void untitled() {
    driver.get("https://www.smile.one/customer/account/login");
    driver.manage().window().setSize(new Dimension(1582, 873));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".vk")).click();
    vars.put("win7061", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win7061").toString());
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("qwflashg@gmail.com");
    driver.findElement(By.name("pass")).sendKeys("vk1101");
    driver.findElement(By.id("install_allow")).click();
    {
      WebElement element = driver.findElement(By.id("install_allow"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
    driver.switchTo().window(vars.get("root").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".listol1 > .list-li:nth-child(3) .imgicon")).click();
    vars.put("win3905", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3905").toString());
    driver.findElement(By.id("puseid")).click();
    driver.findElement(By.id("puseid")).sendKeys("126606687");
    driver.findElement(By.id("pserverid")).sendKeys("2632");
    driver.findElement(By.cssSelector(".PcDiamant-ul > .fl:nth-child(1) > span:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".PcDiamant-ul > .fl:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".section-nav:nth-child(1) .smilecoin > .cartao-name")).click();
    driver.findElement(By.id("Nav-btnpc")).click();
  }
}
